### ISSUE TITLE
Departments.central.edu should have a landing page

### ISSUE THREAD

**Issue by jacoboyen** [CentralCollege/departments-wordpress-theme#53]
We should create a departments.central.edu landing page that properly lists each department website. 

It is important to note that we need to be excessively clear that this is not a listing of majors. Perhaps it is just a listing of administrative departments?

**Comment by jacoboyen** [comment]
This should help with this issue: https://codex.wordpress.org/Function_Reference/wp_get_sites. Implementation into the template may require a custom tag.

**Comment by bohrj** [comment]
Fixed as of Oct. 11, 2018
